USE AdventureWorks
GO

-- TODOS LOS REGISTROS DE LA TABLA 
SELECT * FROM Person.Person

-- SELECCIONA SOLO LOS 10 PRIMEROS REGISTROS
SELECT TOP 10 * FROM Person.Person
SELECT * FROM Person.Person WHERE ROWNUM <=10 --ORACLE
SELECT * FROM Person.Person LIMIT 10 --MYSQL

-- LISTAR EL 10% DE REGISTROS 
SELECT TOP 10 PERCENT * FROM Person.Person --19972 1998

--REGISTROS NO REPETIDOS
SELECT DISTINCT FirstName FROM Person.Person
SELECT DISTINCT FirstName, LastName FROM Person.Person

-- GUARDAR RESULTADO EN OTRAS TABLAS
SELECT DISTINCT FirstName, LastName 
INTO NOMBRES
FROM Person.Person

SELECT * FROM NOMBRES


-- ## GUARDAR LOS REGISTROS EN UN TABLA TEMPORAL LOCAL A NIVEL DE SESION
SELECT DISTINCT FirstName, LastName 
INTO #NOMBRES_TEMP
FROM Person.Person

SELECT * FROM #NOMBRES_TEMP

-- TABLA TEMPORAL GLOBAL 
SELECT DISTINCT FirstName, LastName 
INTO ##NOMBRES_TEMP
FROM Person.Person

-- DROP TABLE #NOMBRES_TEMP

-- CANTIDAD DE REGISTROS VALIDOS
SELECT COUNT(*) FROM Person.Person -- TODAS LAS COLUMNAS DE LAS TABLAS
SELECT COUNT(MiddleName) FROM Person.Person --  NO CUENTRO LO REGISTRO NULOS  --11473

SELECT BusinessEntityID,MiddleName FROM Person.Person 

-- NULL <>  ''

-- NULL TODOS LOS REGISTROS
UPDATE Person.Person
SET MiddleName = NULL

-- VACIO EN TODOS LOS  REGISTROS
/*
UPDATE Person.Person
SET MiddleName = NULL
WHERE BusinessEntityID = 2170
*/

-- CUENTA REGISTRO VALIDOS (NO NULOS)
SELECT COUNT(MiddleName) FROM PERSON.Person   --11475



SELECT FirstName AS NOMBREEMPLEADO, LastName AS APELLIDOEMPLEADO 
FROM Person.Person

SELECT FirstName AS [NOMBRE DEL EMPLEADO], LastName AS [APELLIDO DEL EMPLEADO] 
FROM Person.Person

-- SE PUEDE JUNTAR COLUMNAS SI SON DEL MISMO TIPO DE DATO
SELECT FirstName + ' ' +LastName + 15 AS [APELLIDO DEL EMPLEADO] 
FROM Person.Person


SELECT FirstName + ' ' +LastName + CAST(BusinessEntityID AS varchar)AS [APELLIDO DEL EMPLEADO] 
FROM Person.Person

12345678
123456789123
SELECT 00001235
SELECT '00001235'

"JUAN", "PEREZ","000012475"
SELECT 