CREATE DATABASE DBJOINS
GO

USE DBJOINS
GO

CREATE TABLE TABLA_A
(
 ID INT,
 VALOR CHAR(1)
)
GO 

CREATE TABLE TABLA_B
(
 ID INT,
 VALOR CHAR(1)
)


INSERT INTO TABLA_A VALUES (1,'A')
INSERT INTO TABLA_A VALUES (2,'B')
INSERT INTO TABLA_A VALUES (3,'C')
INSERT INTO TABLA_A VALUES (4,'D')
INSERT INTO TABLA_A VALUES (5,'E')


INSERT INTO TABLA_B VALUES (4,'D')
INSERT INTO TABLA_B VALUES (5,'E')
INSERT INTO TABLA_B VALUES (6,'F')
INSERT INTO TABLA_B VALUES (7,'G')
INSERT INTO TABLA_B VALUES (8,'H')

SELECT *
FROM TABLA_A A
	INNER JOIN TABLA_B B
		ON A.ID = B.ID	


SELECT *
FROM TABLA_A A
	LEFT JOIN TABLA_B B
		ON A.ID = B.ID

SELECT *
FROM TABLA_A A
	RIGHT JOIN TABLA_B B
		ON A.ID = B.ID


-- FULL OUTER JOIN
SELECT *
FROM TABLA_A A
	FULL OUTER JOIN TABLA_B B
		ON A.ID = B.ID

SELECT *
FROM TABLA_A A FULL OUTER JOIN TABLA_B B
ON A.ID = B.ID
WHERE A.ID IS NULL OR B.ID IS NULL


--CROSS APPLY -- ES UN PRODUCTO CARTERSIANO
SELECT * FROM TABLA_A
SELECT * FROM TABLA_B
SELECT * FROM TABLA_A CROSS APPLY TABLA_B
