USE AdventureWorks
GO


-- QUITA DUPLICADOS
/*
TIPO DE DATO CADENA, XML , NUMERICO Y TIENEN QUE TENER LOS MISMOS CAMPOS AMBOS PARA EL QUERY 2
*/
SELECT FirstName
FROM Person.Person 
WHERE FirstName  LIKE 'R%' AND  LastName LIKE 'H%'
UNION
SELECT FirstName
FROM Person.Person 
WHERE MiddleName  = 'M'
GO

USE DBJOINS
GO

SELECT * FROM dbo.TABLA_A
UNION 
SELECT * FROM TABLA_B


SELECT ID, VALOR FROM TABLA_A
UNION ALL
SELECT ID, VALOR FROM TABLA_B

