--ESCRIBA UNA CONSULTA CON FUNCIONES DE VENTANA QUE CALCULE  LAS  VENTAS
-- ACUMULADAS POR CATEGORIA DE PRODUCTOS DE UN AÑO EN PARTICULAR

USE AdventureWorks
GO

SELECT * FROM Sales.SalesOrderHeader
SELECT * FROM Sales.SalesOrderDetail
SELECT * FROM Production.Product
SELECT * FROM Production.ProductSubcategory
GO 

-- FUNCION DE VENTANA
WITH CTE_VENTAS AS 
(
SELECT PS.Name SUBCATEGORIA, MONTH(H.OrderDate) MES, SUM(D.OrderQty * D.UnitPrice) SUBTOTAL
FROM  Sales.SalesOrderHeader H
	INNER JOIN Sales.SalesOrderDetail D ON H.SalesOrderID = D.SalesOrderID
	INNER JOIN Production.Product P ON P.ProductID = D.ProductID
	INNER JOIN Production.ProductSubcategory PS ON P.ProductSubcategoryID = PS.ProductSubcategoryID
WHERE YEAR(H.OrderDate) = 2014
GROUP BY PS.Name, MONTH(H.OrderDate) 
)  

SELECT  SUBCATEGORIA,MES, SUBTOTAL,
SUM(SUBTOTAL) OVER (PARTITION BY SUBCATEGORIA
					ORDER BY SUBCATEGORIA, MES
					ROWS BETWEEN UNBOUNDED PRECEDING
					AND CURRENT ROW) SUMA_SUBTOTAL
FROM CTE_VENTAS
ORDER BY  SUBCATEGORIA, MES