USE AdventureWorks
GO
/*
INT
BIGINT
BIT
CHAR
VARCHAR
DATE
DATETIME
DATETIME2
TIME
*/

SELECT CONVERT(DATE,  SYSDATETIME());
SELECT CONVERT(VARCHAR, SYSDATETIME());

SELECT CONVERT(INT, SYSDATETIME());
-- CONVERT CON LA OPCION DE ESTILO
SELECT CONVERT (DATETIME, '20120212', 102) AS ANSI_STYLE;
SELECT CONVERT (DATETIME, '20120212', 101) AS ANSI_STYLE;
SELECT CONVERT (CHAR(8), CURRENT_TIMESTAMP, 112) AS ISO_STYLE;
SELECT CONVERT (CHAR(80), CURRENT_TIMESTAMP, 100) AS ISO_STYLE;
SELECT PARSE ('01/02/2012' AS datetime2 USING 'en-US') AS PARSE_FAULT; -- CONVIERTE DE ACUERDOA LA CULTURA
SELECT PARSE ('01/02/2012' AS datetime2 USING 'en-GB') AS PARSE_FAULT;
SELECT PARSE ('SQLSERVER' AS datetime2 USING 'en-US') AS PARSE_FAULT;


SELECT ISNUMERIC('101.99') AS INSNUMERIC
SELECT ISNUMERIC('SQLSERVER') AS INSNUMERIC

SELECT IIF(1 = 1,'VERDADERO' ,  IIF(1=2,'X','Y'))
SELECT IIF(1>2,'VERDADERO' , 'FALSO')

SELECT CHOOSE(3, 'Beverages','Condiments','Confections') as  CHOOSE_RESULT;

SELECT TRY_PARSE ('SQLSERVER' AS datetime2 USING 'en-US') AS PARSE_FAULT;


SELECT ISNULL('SQL SERVER','ES NULO')
/*
DECLARE @DIVIDENDO INT
DECLARE @SQL VARCHAR(3000)
SET @DIVIDENDO  = 0 

IF @DIVIDENDO = 0
 @SQL = 'ERROR'
 */

 SELECT  COALESCE('DATO','DAT01') --DEVOLVER EL 1ER VALOR NO NULO
 SELECT  COALESCE(NULL, NULL, NULL, NULL, 'DAT01')


 SELECT NULLIF('DATO','DATO') -- SI SON DIFERENTES DEVUEVE EL 1ER REGISTRO
 SELECT NULLIF('DAOT1','DAOT2')


 USE AdventureWorks
 GO

 SELECT  APPROX_COUNT_DISTINCT(O.LastName)
 FROM DBO.NOMBRES O