--SUBSTRING

SELECT SUBSTRING('SQLSERVER',4,6)

--STUFF
SELECT STUFF('SQLSERVER',4,2,'2019') -- REMPLAZA LA CADENA CON 2 CARACTERES

--LEN -- LOS ESPACIOS HACIA LA DERECHA NO SE CONSIDERA PERO SI LO ESPACIOS 
--A LA IZQUIERDA
SELECT LEN('SQLSERVER        ')
SELECT LEN('        SQLSERVER')

--LEFTH 
SELECT LEFT('SQL SERVER',4)

--RIGHT
SELECT RIGHT('SQL SERVER',4)


--CHARINDEX
SELECT CHARINDEX('SERVER','SQLSERVER')
SELECT CHARINDEX('X','SQLSERVER')

--PATINDEX
SELECT PATINDEX('%SQL%','2019 SQL SERVER') -- BUSQUEDA DE CADENA EN ESTE CADENA EN LA POSICION 6 SE ENCUENTRA LA CADENA


--LOWER 
SELECT LOWER('SqlServer')

--UPPER
SELECT UPPER('SqlServer')

WHERE LOWER(CORREO) = LOWER('JPEREZ@gmail.com  ')

--TRIM (LTRIM, RTRIM)
SELECT LTRIM('		JUAN PEREZ		')
SELECT RTRIM('		JUAN PEREZ		')
SELECT LTRIM(RTRIM('		JUAN PEREZ		'))

-- REPLACE
SELECT REPLACE('SQLSERVER','Q','XYZ')

SELECT REPLACE('D''ALESSANDRO','''','X')


UPDATE Cliente
SET NOMBRE = REPLACE(NOMBRE, '''','X')

--REVERSE
SELECT REVERSE('SQLSERVER')

--REPLICATE
SELECT REPLICATE('SQLSERVER',3)

--SPACE
SELECT SPACE(10)

--CONCAT
SELECT CONCAT('JUAN',SPACE(1),'PEREZ',SPACE(1),'LUQUE')

--DIFFERENCE
SELECT DIFFERENCE('JUAN','juan')
SELECT DIFFERENCE('JUAN','JUAN')
SELECT DIFFERENCE('JUAN','yyyySDFGSFDGSDASDF')
SELECT DIFFERENCE('PEREZ','PERALES')