SELECT GETDATE()


--DATEDIFF 1 AÑO MENOR | 2 AÑO MAYOR
SELECT DATEDIFF(YEAR,'2008/06/30',GETDATE())
SELECT DATEDIFF(DAY,'2008/06/30',GETDATE())
SELECT DATEDIFF(MINUTE,'2008/06/30',GETDATE())

--DATEADD
SELECT DATEADD(DAY,1,GETDATE())
SELECT DATEADD(MONTH,1,GETDATE())
SELECT DATEADD(MONTH,-1,GETDATE())

SELECT MONTH(DATEADD(MONTH,-1,GETDATE()))

--DATEFROMPARTS
SELECT DATEFROMPARTS(2011,05,30)

SELECT EOMONTH(GETDATE()) -- ULTIMO DIA DEL MES
SELECT EOMONTH(GETDATE(),-1) -- ULTIMO DIA DEL MES
SELECT EOMONTH(GETDATE(),1) -- ULTIMO DIA DEL MES

USE AdventureWorks
GO
SELECT * FROM Sales.SalesOrderHeader


SELECT CAST('2008-12-10' AS DATE)

SELECT * 
FROM Sales.SalesOrderHeader
WHERE OrderDate = CAST('21/06/2011' AS DATE)

DECLARE @CADENA VARCHAR(50)
SET @CADENA =  'LUISASDFASDFS MEJIASADFASFDFDS'

SELECT SUBSTRING(@CADENA,1,CHARINDEX(' ',@CADENA)-1)

SELECT SUBSTRING(@CADENA,CHARINDEX(' ',@CADENA)+1,LEN(@CADENA))

